#!/usr/bin/env python3
"""Generate docs/schema_pivots.md from a sys_schema_probe CSV.

Input: a CSV with columns (TableName, ColumnName, ColumnType, ColumnOrdinal) —
produced by `xdr hunt library-run sys_schema_probe` and converted to CSV, or by
the equivalent Advanced Hunting export.

Output: markdown doc with cross-table field intersections, one bullet line per
shared field listing every table it appears in (sorted alphabetically), plus
canonical pivot recipes.

Usage:
    python scripts/build_schema_pivots.py <schema.csv> [output.md]

If output.md is omitted, prints to stdout.
"""

from __future__ import annotations

import csv
import sys
from collections import defaultdict
from pathlib import Path


def load_truth(csv_path: Path) -> dict[str, set[str]]:
    truth: dict[str, set[str]] = defaultdict(set)
    with csv_path.open() as f:
        for row in csv.DictReader(f):
            truth[row["ColumnName"]].add(row["TableName"])
    return truth


def make_line(truth: dict[str, set[str]], rendered: set[str]):
    def line(field: str, note: str | None = None) -> str:
        rendered.add(field)
        tables = truth.get(field)
        if not tables:
            return f"- `{field}` → **(not present in probe)**"
        out = f"- `{field}` → {', '.join(sorted(tables))}"
        if note:
            out += f" — {note}"
        return out
    return line


def build(truth: dict[str, set[str]]) -> str:
    rendered: set[str] = set()
    line = make_line(truth, rendered)
    O: list[str] = []
    p = O.append

    p("# Schema Pivot Reference")
    p("")
    p("Cross-table field intersections for pivoting and hunting across Microsoft 365")
    p("Defender Advanced Hunting tables. Every field lists every table that")
    p("contains it — grep for a table name to find every pivot it supports, or")
    p("grep for a field name to find every table it reaches.")
    p("")
    p("> Regenerate in any tenant:")
    p("> `xdr -q hunt library-run sys_schema_probe --limit 10000 > schema.json`")
    p(">")
    p("> The probe covers **80 curated Defender XDR, Sentinel, and Entra workspace")
    p("> tables**; which are returned varies by license, role, connected workspace,")
    p("> and connector. `sys_schema_probe` uses `union isfuzzy=true`, so absent tables")
    p("> are silently skipped. Custom logs and future workspace tables must be added to")
    p("> the probe explicitly. Re-run after any licensing or connector change.")
    p("")
    p("> Rebuilding this doc: `python scripts/build_schema_pivots.py <schema.csv> docs/schema_pivots.md`.")
    p("")
    p("---")
    p("")
    p("## Casing gotchas — read first")
    p("")
    p("Column names are case-sensitive in KQL joins. A few near-duplicates trip up")
    p("cross-table queries:")
    p("")
    p(line("IPAddress", "all-caps — the dominant form."))
    p(line("IpAddress", "camelCase `p` — `DisruptionAndResponseEvents` and `GraphAPIAuditEvents` use this spelling instead of `IPAddress`. `DisruptionAndResponseEvents` also has `SourceIpAddress` and plain `Port`/`SourcePort`."))
    p(line("Categories", "dynamic array in most tables, but `AlertInfo` uses scalar `Category` (singular) instead."))
    p("")
    p("When unioning across these boundaries, normalize: `extend IpAddr = coalesce(IPAddress, IpAddress)`.")
    p("")
    p("---")
    p("")
    p("## Tenant variance - columns that may be absent")
    p("")
    p("Some columns appear in Microsoft's public schema documentation but are not")
    p("consistently populated or even present across all tenants. License tier,")
    p("region, and table version determine availability. Columns to sanity-check")
    p("before using:")
    p("")
    p("- `IsAnonymousProxy`, `IsExternalDevice` are documented for")
    p("  `AADSignInEventsBeta` but are absent on some tenants. Projecting them")
    p("  causes `Failed to resolve scalar expression` (API 400).")
    p("- `RawEventData.CountryCode` is populated for some `CloudAppEvents` sources")
    p("  (for example, Entra sign-in-derived rows) and null for others.")
    p("- `DetectionMethods` is documented for `EmailEvents`, but the table itself")
    p("  may be empty in tenants without Defender for Office licenses.")
    p("")
    p("Before referencing an unfamiliar column, run `xdr hunt library-run")
    p("sys_schema_probe` or test with `getschema`:")
    p("")
    p("```kql")
    p("AADSignInEventsBeta | getschema | where ColumnName in ('IsAnonymousProxy', 'IsExternalDevice')")
    p("```")
    p("")
    p("An empty result means the column is not in this tenant's schema - pick an")
    p("available alternative (`IsCompliant`, `AuthenticationRequirement`,")
    p("`ConditionalAccessStatus`) or drop the projection.")
    p("")
    p("---")
    p("")
    p("## Row identity (uniqueness contracts)")
    p("")
    p("Uniqueness contracts come from Microsoft's Advanced Hunting docs, not from")
    p("the probe — `getschema` only reports columns, not keys.")
    p("")
    p(line("ReportId", "**not unique alone**; MDE event identity is `(DeviceId, ReportId, Timestamp)`. Many other tables have their own ReportId semantics."))
    p(line("Timestamp", "always narrow by time window before joins."))
    p(line("AlertId", "one `AlertInfo` row per alert, many `AlertEvidence` rows."))
    p(line("BehaviorId", "one `BehaviorInfo` row per behavior, many `BehaviorEntities` rows; also used by `DataSecurityBehaviors`."))
    p(line("NetworkMessageId", "spine of the email chain; `CampaignInfo` and `DataSecurityEvents` ride it too."))
    p(line("InternetMessageId", "RFC-5322 `Message-ID`."))
    p(line("TeamsMessageId", "spine of the Teams chain."))
    p(line("CampaignId"))
    p(line("RequestId", "Entra sign-in request ID; joins Entra twins + Graph audit."))
    p(line("CorrelationId", "Entra sign-in correlation ID across user + SPN + new/legacy Entra tables."))
    p(line("SessionId"))
    p(line("OperationId"))
    p(line("ActivityId"))
    p(line("UniqueTokenId"))
    p("")
    p("---")
    p("")
    p("## Ingestion and tenancy metadata")
    p("")
    p("These fields describe the hunting data pipeline rather than an entity pivot.")
    p("Use them for ingestion and billing analysis, not event correlation:")
    p("")
    p(line("MachineGroup"))
    p(line("SourceSystem"))
    p(line("TenantId"))
    p(line("TenantMembershipType"))
    p(line("TimeGenerated"))
    p(line("_BilledSize"))
    p(line("_IsBillable"))
    p(line("_ItemId"))
    p(line("_ResourceId"))
    p(line("_SubscriptionId"))
    p(line("_TimeReceived"))
    p("")
    p("---")
    p("")
    p("## Device identity")
    p("")
    p(line("DeviceId", "prefer as MDE join key."))
    p(line("DeviceName", "human-readable, rename-unsafe; filter/display only."))
    p(line("AadDeviceId", "Entra join key — device ↔ Azure AD object."))
    p(line("EntraIdDeviceId", "new Entra device ID (equivalent to `AadDeviceId` in Entra sign-in tables)."))
    p("")
    p("## OS / device facets")
    p("")
    p(line("OSPlatform"))
    p(line("OSArchitecture"))
    p(line("OSVersion"))
    p(line("DeviceType"))
    p(line("Platform"))
    p("")
    p("---")
    p("")
    p("## Cloud resource identity (Defender for Cloud — multi-cloud)")
    p("")
    p("MDC tables (`CloudAuditEvents`, `CloudDnsEvents`, `CloudProcessEvents`,")
    p("`CloudStorageAggregatedEvents`) don't carry `DeviceId`. They identify the")
    p("workload by cloud-native resource ID:")
    p("")
    p(line("AzureResourceId", "also present in `DeviceInfo` — the Azure VM join bridge."))
    p(line("AwsResourceName"))
    p(line("GcpFullResourceName"))
    p("")
    p("`CloudProcessEvents` mirrors MDE process telemetry with a workload")
    p("identifier — bridge MDE ↔ cloud via `AzureResourceId` (from `DeviceInfo`")
    p("to `CloudProcessEvents`), then pivot on `ProcessCommandLine` / `FileName` /")
    p("`AccountName`.")
    p("")
    p("Container / Kubernetes context (MDC `CloudDnsEvents` ↔ `CloudProcessEvents`):")
    p("")
    p(line("ContainerId"))
    p(line("ContainerName"))
    p(line("KubernetesNamespace"))
    p(line("KubernetesPodName"))
    p(line("KubernetesResource"))
    p(line("ProcessName"))
    p("")
    p("MDC cloud-audit plumbing:")
    p("")
    p(line("AuditSource"))
    p(line("DataSource"))
    p(line("IsAnonymousProxy"))
    p("")
    p("---")
    p("")
    p("## User / account identity")
    p("")
    p(line("AccountObjectId", "Entra OID — strongest cross-surface pivot (Entra sign-ins ↔ MDI ↔ MDCA ↔ DLP ↔ Graph audit ↔ alerts ↔ device processes)."))
    p(line("AccountUpn", "human-readable UPN; reaches click telemetry, MDI, MDCA, DLP, Entra sign-ins."))
    p(line("AccountSid", "Windows SID, device-side + MDI."))
    p(line("AccountName", "pair with `AccountDomain`."))
    p(line("AccountDomain", "pair with `AccountName`."))
    p(line("AccountDisplayName", "display name; filter/display only."))
    p(line("AccountId", "MDI/Cloud account identifier (different from `AccountObjectId`)."))
    p(line("AccountType"))
    p(line("IdentityId", "`IdentityInfo` + `IdentityAccountInfo` identity key."))
    p(line("AlternateSignInName"))
    p(line("IsExternalUser"))
    p(line("IsGuestUser"))
    p("")
    p("MDI target-entity fields (actor + target shape):")
    p("")
    p(line("TargetAccountUpn"))
    p(line("TargetAccountDisplayName"))
    p(line("TargetDeviceName"))
    p(line("TargetDomainName"))
    p(line("DestinationDeviceName"))
    p(line("DestinationIPAddress"))
    p(line("DestinationPort"))
    p("")
    p("`DisruptionAndResponseEvents` has its own Source/Target shape:")
    p("")
    p(line("SourceDeviceId"))
    p(line("TargetDeviceId"))
    p(line("SourceDeviceName"))
    p(line("SourceDomainName"))
    p(line("SourceUserSid"))
    p(line("SourceUserName"))
    p(line("SourceUserDomainName"))
    p(line("SourceIpAddress", "camelCase `p` — not `IPAddress`."))
    p(line("SourcePort"))
    p("")
    p("---")
    p("")
    p("## Service principals / OAuth apps")
    p("")
    p(line("ApplicationId"))
    p(line("Application"))
    p(line("AppName"))
    p(line("OAuthAppId", "join to Entra SPN sign-ins via `ServicePrincipalId`."))
    p(line("OAuthApplicationId"))
    p(line("ServicePrincipalId"))
    p(line("ServicePrincipalName"))
    p(line("ApplicationInstanceId"))
    p(line("ApplicationEventId"))
    p(line("ApplicationSessionId"))
    p(line("ResourceDisplayName"))
    p(line("ResourceId"))
    p(line("ResourceTenantId", "tenant of the resource the token was issued for."))
    p(line("AppOwnerTenantId"))
    p("")
    p("---")
    p("")
    p("## Initiating process bundle (25 fields across the same 7 device tables)")
    p("")
    p("Every field below is present in exactly these 7 tables: **DeviceEvents,")
    p("DeviceFileEvents, DeviceImageLoadEvents, DeviceLogonEvents,")
    p("DeviceNetworkEvents, DeviceProcessEvents, DeviceRegistryEvents**.")
    p("")
    bundle_7 = [
        "InitiatingProcessAccountDomain", "InitiatingProcessAccountName",
        "InitiatingProcessAccountObjectId", "InitiatingProcessAccountSid",
        "InitiatingProcessAccountUpn", "InitiatingProcessCommandLine",
        "InitiatingProcessCreationTime", "InitiatingProcessFileSize",
        "InitiatingProcessFolderPath", "InitiatingProcessMD5",
        "InitiatingProcessParentCreationTime", "InitiatingProcessParentFileName",
        "InitiatingProcessParentId", "InitiatingProcessRemoteSessionDeviceName",
        "InitiatingProcessRemoteSessionIP", "InitiatingProcessSHA1",
        "InitiatingProcessSHA256", "InitiatingProcessSessionId",
        "InitiatingProcessUniqueId", "InitiatingProcessVersionInfoCompanyName",
        "InitiatingProcessVersionInfoFileDescription",
        "InitiatingProcessVersionInfoInternalFileName",
        "InitiatingProcessVersionInfoOriginalFileName",
        "InitiatingProcessVersionInfoProductName",
        "InitiatingProcessVersionInfoProductVersion",
        "IsInitiatingProcessRemoteSession", "AppGuardContainerId",
    ]
    for f in bundle_7:
        p(line(f))
    p("")
    p("Extended (8–9 tables — also in `CloudProcessEvents` + `DisruptionAndResponseEvents`):")
    p("")
    p(line("InitiatingProcessFileName"))
    p(line("InitiatingProcessId"))
    p("")
    p("Subset (6 of 7 — missing from `DeviceEvents`):")
    p("")
    p(line("InitiatingProcessIntegrityLevel"))
    p(line("InitiatingProcessTokenElevation"))
    p("")
    p("Canonical unique process identity on a device:")
    p("`(DeviceId, InitiatingProcessId, InitiatingProcessCreationTime)`.")
    p("")
    p("## Created-process bundle")
    p("")
    p(line("CreatedProcessSessionId"))
    p(line("ProcessCreationTime"))
    p(line("ProcessId", "also in `CloudProcessEvents` + `CloudDnsEvents` — cloud workload process id, not DeviceId-scoped."))
    p(line("ProcessRemoteSessionDeviceName"))
    p(line("ProcessRemoteSessionIP"))
    p(line("ProcessTokenElevation"))
    p(line("IsProcessRemoteSession"))
    p(line("InitiatingProcessLogonId"))
    p(line("ProcessCommandLine", "also in `CloudProcessEvents`."))
    p(line("LogonId", "`DisruptionAndResponseEvents` and `CloudProcessEvents` extend the MDE logon trio."))
    p("")
    p("---")
    p("")
    p("## File identity")
    p("")
    p(line("SHA256", "canonical file pivot; reaches `FileMaliciousContentInfo` too."))
    p(line("SHA1", "only hash that joins `DeviceFileCertificateInfo` (code signing)."))
    p(line("MD5", "legacy."))
    p(line("FileName"))
    p(line("FolderPath"))
    p(line("FileSize"))
    p(line("FileOriginIP"))
    p(line("FileOriginUrl"))
    p(line("FileOwnerUpn"))
    p(line("DocumentID"))
    p("")
    p("---")
    p("")
    p("## Network — device-side (MDE)")
    p("")
    p(line("RemoteIP"))
    p(line("LocalIP"))
    p(line("RemoteUrl"))
    p(line("RemotePort"))
    p(line("LocalPort"))
    p(line("Protocol"))
    p(line("RemoteIPType"))
    p(line("RemoteDeviceName"))
    p(line("ShareName", "device file-share activity, also surfaces in `DisruptionAndResponseEvents`."))
    p("")
    p("## Network — identity / sign-in / cloud-apps")
    p("")
    p("Distinct shape from device-side `Remote*`/`Local*` — actor-centric source")
    p("IP + port, `Destination*` / `Target*` for the target.")
    p("")
    p(line("IPAddress", "see casing gotchas above."))
    p(line("IpAddress", "camelCase `p` variant."))
    p(line("Port"))
    p(line("UserAgent"))
    p(line("GatewayJA4"))
    p("")
    p("---")
    p("")
    p("## Logon correlation (device ↔ identity ↔ Entra sign-in)")
    p("")
    p(line("LogonType", "MDE `DeviceLogonEvents` ↔ MDI `IdentityLogonEvents` ↔ Entra `AADSignInEventsBeta`/`EntraIdSignInEvents` ↔ `DisruptionAndResponseEvents`."))
    p(line("LogonId"))
    p(line("FailureReason"))
    p(line("ActionFailureReason"))
    p(line("ErrorCode", "Entra sign-in failure code (user + SPN, legacy + new)."))
    p("")
    p("## Sign-in events — Entra twins (user)")
    p("")
    p("`AADSignInEventsBeta` and `EntraIdSignInEvents` are schema-compatible twins")
    p("(legacy vs new). Prefer `EntraIdSignInEvents` when available.")
    p("")
    for f in [
        "RiskLevelAggregated", "RiskLevelDuringSignIn", "RiskEventTypes",
        "RiskState", "ConditionalAccessPolicies", "ConditionalAccessStatus",
        "AuthenticationProcessingDetails", "AuthenticationRequirement",
        "TokenIssuerType", "ClientAppUsed", "Browser", "DeviceTrustType",
        "IsManaged", "IsCompliant", "EndpointCall", "EntraIdDeviceId",
        "NetworkLocationDetails", "LastPasswordChangeTimestamp",
    ]:
        p(line(f))
    p("")
    p("## Sign-in events — Entra twins (service principal)")
    p("")
    p("`AADSpnSignInEventsBeta` and `EntraIdSpnSignInEvents` — workload identity sign-ins.")
    p("")
    p(line("IsManagedIdentity"))
    p(line("IsConfidentialClient"))
    p("")
    p("---")
    p("")
    p("## Geo enrichment")
    p("")
    p(line("Country"))
    p(line("CountryCode"))
    p(line("State"))
    p(line("City"))
    p(line("Latitude"))
    p(line("Longitude"))
    p(line("Location"))
    p(line("ISP"))
    p("")
    p("---")
    p("")
    p("## Email chain")
    p("")
    p("`NetworkMessageId` is the spine — `EmailEvents` → `EmailAttachmentInfo` →")
    p("`EmailUrlInfo` → `EmailPostDeliveryEvents` → `UrlClickEvents` →")
    p("`CampaignInfo` → `DataSecurityEvents` (+ `AlertEvidence` / `BehaviorEntities`")
    p("for XDR fusion).")
    p("")
    for f in [
        "NetworkMessageId", "InternetMessageId", "RecipientEmailAddress",
        "SenderFromAddress", "RecipientObjectId", "SenderObjectId",
        "SenderDisplayName", "Url", "UrlDomain", "EmailDirection",
        "DeliveryLocation", "DeliveryAction", "LatestDeliveryLocation",
        "LatestDeliveryAction", "EmailClusterId", "EmailSubject", "Subject",
    ]:
        p(line(f))
    p("")
    p("## Campaigns (MDO)")
    p("")
    p(line("CampaignId"))
    p(line("CampaignName"))
    p(line("CampaignType"))
    p(line("CampaignSubType"))
    p("")
    p("Join `CampaignInfo` to the email chain on `NetworkMessageId`.")
    p("")
    p("---")
    p("")
    p("## Teams chain")
    p("")
    p("`TeamsMessageId` is the spine for `MessageEvents` / `MessagePostDeliveryEvents`")
    p("/ `MessageUrlInfo`. These do **not** share `NetworkMessageId` — pivot only")
    p("on `TeamsMessageId` within the Teams set.")
    p("")
    p(line("TeamsMessageId"))
    p(line("SenderEmailAddress"))
    p(line("RecipientDetails", "dynamic — `parse_json` or `mv-expand`."))
    p(line("IsExternalThread"))
    p(line("SafetyTip"))
    p(line("ConfidenceLevel"))
    p(line("MessageType", "also used by `ConnectorStatusInfo` (unrelated semantic — connector message type)."))
    p("")
    p("Cross-link to users/accounts via `SenderObjectId` (shared with email chain).")
    p("")
    p("---")
    p("")
    p("## Registry")
    p("")
    p(line("RegistryKey"))
    p(line("RegistryValueName"))
    p(line("RegistryValueData"))
    p("")
    p("---")
    p("")
    p("## TVM — software inventory")
    p("")
    p(line("SoftwareName"))
    p(line("SoftwareVendor"))
    p(line("SoftwareVersion"))
    p("")
    p("## TVM — vulnerabilities (device data ↔ CVE KB)")
    p("")
    p(line("CveId"))
    p(line("VulnerabilitySeverityLevel"))
    p("")
    p("## TVM — secure-config assessment (data ↔ KB)")
    p("")
    p(line("ConfigurationId", "also in `DeviceBaselineCompliance*` — same field name, different semantic."))
    p(line("ConfigurationCategory"))
    p(line("ConfigurationSubcategory"))
    p(line("ConfigurationImpact"))
    p("")
    p("## TVM — info-gathering")
    p("")
    p(line("LastSeenTime"))
    p("")
    p("## TVM — browser extensions (device evidence ↔ KB)")
    p("")
    p(line("BrowserName"))
    p(line("ExtensionId"))
    p(line("ExtensionName"))
    p(line("ExtensionDescription"))
    p(line("ExtensionVersion"))
    p(line("ExtensionRisk"))
    p("")
    p("## Device baseline compliance (new)")
    p("")
    p(line("ProfileId"))
    p(line("IsCompliant", "shared with TVM secure-config + Entra sign-ins."))
    p(line("IsApplicable"))
    p(line("AssessmentMethod"))
    p(line("RecommendedValue"))
    p(line("Source"))
    p("")
    p("Baseline KB ↔ TVM secure-config KB share control metadata:")
    p("")
    p(line("ConfigurationName"))
    p(line("ConfigurationDescription"))
    p(line("RemediationOptions"))
    p("")
    p("---")
    p("")
    p("## Cloud apps (MDCA)")
    p("")
    p(line("Application"))
    p(line("ApplicationId"))
    p(line("OAuthApplicationId"))
    p("")
    p("---")
    p("")
    p("## Alerts & behaviors fan-out")
    p("")
    for f in [
        "AlertId", "Title", "Severity", "SentinelWorkspaceIds",
        "ServiceSource", "DetectionSource", "AttackTechniques",
        "BehaviorId", "DataSources",
    ]:
        p(line(f))
    p(line("Categories", "`AlertInfo` uses scalar `Category` (singular), not the `Categories` array."))
    for f in [
        "ActionType", "Action", "ActionCategory", "ActionResult", "ActionTrigger",
        "EntityType", "EntityRole", "DetailedEntityRole", "EvidenceRole",
        "EvidenceDirection", "ThreatFamily", "CloudResource",
        "CloudPlatform", "ResourceType", "ResourceID", "SubscriptionId",
        "StartTime", "EndTime",
    ]:
        p(line(f))
    p("")
    p("---")
    p("")
    p("## Email / file / message threat metadata")
    p("")
    p(line("DetectionMethods"))
    p(line("ThreatTypes"))
    p(line("ThreatNames"))
    p(line("ThreatClassification"))
    p("")
    p("---")
    p("")
    p("## Data security (Purview DLP / insider risk)")
    p("")
    p("`DataSecurityEvents` and `DataSecurityBehaviors` cross-link to alerts via")
    p("`AttackTechniques` / `ServiceSource` / `DetectionSource` / `Categories`,")
    p("to email via `NetworkMessageId` / `InternetMessageId`, to users via")
    p("`AccountObjectId` / `AccountUpn`.")
    p("")
    p(line("SensitivityLabelId"))
    p(line("SensitivityLabel"))
    p(line("SensitivitySubLabel"))
    p(line("ObjectId", "DLP-scoped content id; also used by `CloudAppEvents`."))
    p(line("PrinterName"))
    p("")
    p("---")
    p("")
    p("## Attack disruption")
    p("")
    p("`DisruptionAndResponseEvents` logs automatic attack-disruption actions")
    p("(user disable, device contain). Pivots on its Source/Target shape (see")
    p("*User / account identity* above) and on `PolicyId` / `PolicyName` /")
    p("`CompromisedAccountCount` (per-table).")
    p("")
    p("---")
    p("")
    p("## File threat intel")
    p("")
    p("`FileMaliciousContentInfo` joins endpoint + email file events via")
    p("`SHA256`, `FileName`, `FileSize`, `FolderPath`. See *File identity*.")
    p("")
    p("---")
    p("")
    p("## Risk signals")
    p("")
    p(line("IsAnomalous"))
    p(line("IsPolicyOn"))
    p(line("CompromisedAccountCount"))
    p("")
    p("---")
    p("")
    p("## Anomaly flags (dynamic)")
    p("")
    p(line("UncommonForUser", "MDCA/MDI per-event anomaly signal; `parse_json` before filtering."))
    p(line("LastSeenForUser", "complements `UncommonForUser`; last-observed baseline."))
    p("")
    p("---")
    p("")
    p("## Multi-valued / JSON fields (require `mv-expand` or `parse_json`)")
    p("")
    p("Filtering these with `==` or `contains` silently misses matches. Normalize")
    p("first.")
    p("")
    mv = [
        "AdditionalFields", "RawEventData", "Categories", "AttackTechniques",
        "ThreatTypes", "DetectionMethods", "DataSources", "SentinelWorkspaceIds",
        "Tags", "ThreatNames", "UncommonForUser", "LastSeenForUser", "IPTags",
        "UserAgentTags", "ActivityObjects", "SessionData",
        "ConditionalAccessPolicies", "Permissions", "GroupMembership",
        "AssignedRoles", "KnowledgeDetails", "AgentTopicsDetails",
        "AgentToolsDetails", "ConnectedAgentsSchemaNames",
        "ChildAgentsSchemaNames", "AccessCapabilities", "PolicyMatchInfo",
        "DlpPolicyMatchInfo", "DlpPolicyRuleMatchInfo", "SensitivityLabelInfo",
        "SensitiveInfoTypesInfo", "SharepointSiteInfo", "RemovableMediaInfo",
        "UrlDomainInfo", "DeviceInfo", "RecipientDetails", "EnrolledMfas",
        "EligibleRoles", "TargetObjects",
    ]
    for f in mv:
        p(line(f))
    p("")
    p("---")
    p("")
    p("## Misc shared fields")
    p("")
    misc = [
        "Description", "Context", "LastModifiedTime", "Workload", "Manager",
        "Department", "CreatedDateTime", "DeletedDateTime", "EmployeeId",
        "GivenName", "Surname", "JobTitle", "Address", "Phone", "EmailAddress",
        "DisplayName", "CriticalityLevel", "SourceProvider", "Type",
        "BlastRadius", "RiskLevel", "RiskScore", "RiskLevelDetails",
        "RiskScoreUpdateTime", "IdentityEnvironment", "SourceProviders",
    ]
    for f in misc:
        p(line(f))
    p("")
    p("---")
    p("")
    p("## Additional shared fields")
    p("")
    p("Shared fields outside the curated pivot categories above. These are")
    p("generated directly from the tenant schema so connected workspace tables")
    p("and custom logs remain represented without manual renderer changes.")
    p("")
    for field in sorted(
        field for field, tables in truth.items()
        if len(tables) >= 2 and field not in rendered
    ):
        p(line(field))
    p("")
    p("---")
    p("")
    p("## Worked pivot recipes")
    p("")
    p("**1) Hash → everywhere it ran (endpoint + email + TI):**")
    p("```kql")
    p('let h = "SHA256_HERE";')
    p("union")
    p('  (DeviceProcessEvents      | where SHA256 == h | project Timestamp, Table="DeviceProcessEvents",      DeviceName, AccountUpn=InitiatingProcessAccountUpn, FileName, FolderPath),')
    p('  (DeviceFileEvents         | where SHA256 == h | project Timestamp, Table="DeviceFileEvents",         DeviceName, AccountUpn=InitiatingProcessAccountUpn, FileName, FolderPath),')
    p('  (DeviceImageLoadEvents    | where SHA256 == h | project Timestamp, Table="DeviceImageLoadEvents",    DeviceName, AccountUpn=InitiatingProcessAccountUpn, FileName, FolderPath),')
    p('  (EmailAttachmentInfo      | where SHA256 == h | project Timestamp, Table="EmailAttachmentInfo",      DeviceName=tostring(dynamic(null)), AccountUpn=RecipientEmailAddress, FileName, FolderPath=tostring(dynamic(null))),')
    p('  (FileMaliciousContentInfo | where SHA256 == h | project Timestamp, Table="FileMaliciousContentInfo", DeviceName=tostring(dynamic(null)), AccountUpn=FileOwnerUpn, FileName, FolderPath)')
    p("| order by Timestamp asc")
    p("```")
    p("")
    p("**2) Entra sign-in ↔ MDE logon correlation (same UPN, same window):**")
    p("```kql")
    p("EntraIdSignInEvents")
    p("| where Timestamp > ago(1h) and ErrorCode == 0")
    p("| project EntraTime=Timestamp, AccountUpn, EntraIP=IPAddress, EntraCity=City, DeviceTrustType, IsCompliant")
    p("| join kind=inner (")
    p('  DeviceLogonEvents | where Timestamp > ago(1h) and ActionType == "LogonSuccess"')
    p("  | extend AccountUpn = strcat(AccountName, \"@\", AccountDomain)")
    p("  | project DeviceTime=Timestamp, DeviceName, AccountUpn, DeviceLogonType=LogonType, DeviceRemoteIP=RemoteIP")
    p("  ) on AccountUpn")
    p("| where abs(datetime_diff('second', EntraTime, DeviceTime)) < 300")
    p("```")
    p("")
    p("**3) OAuth app compromise triangulation (app ↔ SPN sign-ins ↔ Graph calls):**")
    p("```kql")
    p("OAuthAppInfo")
    p('| where AppName has "SuspectApp"')
    p("| project OAuthAppId, ServicePrincipalId, Permissions, IsAdminConsented, ConsentedUsersCount")
    p("| join kind=inner (")
    p("  EntraIdSpnSignInEvents | project SpnTime=Timestamp, ServicePrincipalId, ApplicationId, IPAddress, Country, ErrorCode")
    p("  ) on ServicePrincipalId")
    p("| join kind=leftouter (")
    p("  GraphAPIAuditEvents | project GraphTime=Timestamp, ServicePrincipalId, RequestUri, ResponseStatusCode, RequestMethod, Scopes")
    p("  ) on ServicePrincipalId")
    p("| order by SpnTime asc")
    p("```")
    p("")
    p("**4) Cloud workload → process activity (MDC ↔ MDE by Azure resource):**")
    p("```kql")
    p("DeviceInfo")
    p('| where isnotempty(AzureResourceId)')
    p("| project DeviceId, DeviceName, AzureResourceId")
    p("| join kind=inner (")
    p("  CloudProcessEvents | project CloudTime=Timestamp, AzureResourceId, ProcessCommandLine, FileName, AccountName, LogonId")
    p("  ) on AzureResourceId")
    p("| project CloudTime, DeviceName, AccountName, FileName, ProcessCommandLine")
    p("```")
    p("")
    p("**5) Email campaign → endpoints that opened a link:**")
    p("```kql")
    p("EmailEvents")
    p('| where NetworkMessageId in ("MSG_ID1","MSG_ID2")')
    p("| join kind=inner UrlClickEvents on NetworkMessageId")
    p("| project ClickTime=Timestamp1, AccountUpn, Url, NetworkMessageId, Subject")
    p("```")
    p("")
    p("**6) Entra user → every surface they touched:**")
    p("```kql")
    p('let oid = toscalar(IdentityInfo | where AccountUpn == "user@domain.com" | take 1 | project AccountObjectId);')
    p("union")
    p('  (DeviceProcessEvents     | where AccountObjectId == oid | project Timestamp, Table="DeviceProcessEvents",     Detail=ProcessCommandLine),')
    p('  (IdentityLogonEvents     | where AccountObjectId == oid | project Timestamp, Table="IdentityLogonEvents",     Detail=strcat(LogonType, " from ", IPAddress)),')
    p('  (IdentityDirectoryEvents | where AccountObjectId == oid | project Timestamp, Table="IdentityDirectoryEvents", Detail=ActionType),')
    p('  (EntraIdSignInEvents     | where AccountObjectId == oid | project Timestamp, Table="EntraIdSignInEvents",     Detail=strcat(Application, " @ ", IPAddress, " err=", tostring(ErrorCode))),')
    p('  (CloudAppEvents          | where AccountObjectId == oid | project Timestamp, Table="CloudAppEvents",          Detail=strcat(Application, " / ", ActionType)),')
    p('  (GraphAPIAuditEvents     | where AccountObjectId == oid | project Timestamp, Table="GraphAPIAuditEvents",     Detail=strcat(RequestMethod, " ", RequestUri)),')
    p('  (AlertEvidence           | where AccountObjectId == oid | project Timestamp, Table="AlertEvidence",           Detail=strcat(Title, " [", Severity, "]"))')
    p("| order by Timestamp asc")
    p("```")
    p("")
    p("**7) Alert → all evidence → device timeline around the event:**")
    p("```kql")
    p("AlertInfo")
    p('| where AlertId == "ALERT_ID"')
    p("| join kind=inner AlertEvidence on AlertId")
    p("| where isnotempty(DeviceId) and isnotempty(Timestamp)")
    p("| project AlertId, DeviceId, PivotFrom=Timestamp")
    p("| join kind=inner (")
    p("    DeviceEvents | project DeviceId, Timestamp, ActionType, FileName, ProcessCommandLine")
    p("  ) on DeviceId")
    p("| where Timestamp between (PivotFrom - 10m .. PivotFrom + 10m)")
    p("```")
    p("")
    p("**8) CVE → vulnerable devices with CVSS / exploit context:**")
    p("```kql")
    p("DeviceTvmSoftwareVulnerabilitiesKB")
    p('| where CveId == "CVE-YYYY-NNNNN"')
    p("| project CveId, CvssScore, IsExploitAvailable, VulnerabilityDescription")
    p("| join kind=inner DeviceTvmSoftwareVulnerabilities on CveId")
    p("| project DeviceName, SoftwareName, SoftwareVersion, CveId, CvssScore, IsExploitAvailable")
    p("```")

    return "\n".join(O) + "\n"


def main(argv: list[str]) -> int:
    if len(argv) < 2 or argv[1] in {"-h", "--help"}:
        print(__doc__)
        return 1
    csv_path = Path(argv[1])
    if not csv_path.exists():
        print(f"error: {csv_path} not found", file=sys.stderr)
        return 2
    truth = load_truth(csv_path)
    doc = build(truth)
    if len(argv) >= 3:
        Path(argv[2]).write_text(doc)
    else:
        sys.stdout.write(doc)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
